baseURL: https://imleowoo.github.io/  # ç«™ç‚¹åœ°å€
languageCode: zh # è¯­è¨€ç¼–ç 
title: LEO'S NOTES  # ç«™ç‚¹æ ‡é¢˜
theme: PaperMod # ç«™ç‚¹ä¸»é¢˜

enableInlineShortcodes: true
enableRobotsTXT: true # æ˜¯å¦å¯ç”¨ robots.txt
hasCJKLanguage: true # è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å« ä¸­æ–‡æ—¥æ–‡éŸ©æ–‡
buildDrafts: false # æ˜¯å¦ç”Ÿæˆæ ‡è®°ä¸ºè‰ç¨¿çš„æ–‡ç« 
buildFuture: false
buildExpired: false
enableEmoji: true # æ˜¯å¦å¯ç”¨ emoji è¡¨æƒ…ç¬¦å·
pygmentsUseClasses: true # å¯ç”¨ pygments è¯­æ³•é«˜äº®
googleAnalytics: G-JCECJ36CP1

minify:
  disableXML: true # ç¦ç”¨XMLå‹ç¼©
  # minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON


params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "åšäº†ä¸€ä¸ªæ¢¦ï¼Œä¹±åˆ°è®²ä¸å‡ºæ¥ã€‚"
  author: Leo
  # author: ["Me", "You"] # multiple authors
  keywords: [ Blog, Note, life ]

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true # æ˜¾ç¤ºç›®å½•
  # UseHugoToc: true
  # TocOpen: true # è‡ªåŠ¨å±•å¼€ç›®å½•
  comments: true
  hideSummary: false
  images: [ "papermod-cover.png" ]

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "https://s.gravatar.com/avatar/b82c43aac27a4b77c9558be2c1748243?s=320" # ä½¿ç”¨ Gravatar çš„å¤´åƒ
    favicon: "https://avatars.githubusercontent.com/u/33342014"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"


  profileMode:
    enabled: true
    title: I'M LEO
    imageUrl: "https://avatars.githubusercontent.com/u/33342014"
    imageTitle: cover
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: ç¬”è®°
        url: post
      - name: åˆ†ç±»
        url: categories

  homeInfoParams:
    Title: "LEO'S NOTES"
    Content: >
      Welcome to LEO'S NOTES.

  socialIcons: # ç¤¾äº¤å¹³å°å›¾æ ‡
    - name: github
      url: "https://github.com/imleowoo"
    - name: email
      url: "mailto:imleowoo@outlook.com"
    - name: bilibili
      url: "https://space.bilibili.com/29814200"
    - name: douban
      url: "https://www.douban.com/people/leowooe"
    - name: Rss
      url: "index.xml"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]


menu:
  main:
    - identifier: home
      name: ä¸»é¡µ
      url: /
      weight: 10
    - identifier: posts
      name: ç¬”è®°
      url: /posts/
      weight: 20
    - identifier: categories
      name: åˆ†ç±»
      url: /categories/
      weight: 30
    - identifier: tags
      name: æ ‡ç­¾
      url: /tags/
      weight: 40
    - identifier: archives
      name: æ—¶é—´è½´
      url: /archives/
      weight: 50
    - identifier: about
      name: å…³äº
      url: /about/
      weight: 60
    #    - identifier: links
    #      name: å‹é“¾
    #      url: /links/
    #      weight: 60
    - identifier: search
      name: æœç´¢ ğŸ”
      url: /search/
      weight: 100


#  analytics:
#    google:
#      SiteVerificationTag: "XYZabc"
#    bing:
#      SiteVerificationTag: "XYZabc"
#    yandex:
#      SiteVerificationTag: "XYZabc"

